/**
 * Talent Map layer architecture v0.2 (Stage 4.7+).
 *
 * Catalogs and static mappings: 19-step runtime → 16 product narrative layers + data_quality
 * → 6 synthesis blocks. Used by Product Layer Adapter v0.2 and synthesis_blocks v0.1.
 *
 * @see README_LAYER_ARCHITECTURE_V0_2.md
 */

import type { HrTalentMapSynthesisBlocksV2 } from "./types";

export const LAYER_ARCHITECTURE_VERSION = "0.2" as const;
export const PRODUCT_LAYER_CATALOG_VERSION = "product_layer_catalog_v0_2" as const;
export const EVIDENCE_SIGNAL_CATALOG_VERSION = "evidence_signal_catalog_v0_2" as const;

/** Keys generated by the core-layers background pipeline (12 source + 7 product narrative). */
export const RUNTIME_CORE_LAYER_KEYS = [
  "work_format",
  "task_entry",
  "decision_style",
  "work_signature",
  "inner_coherence",
  "stable_zones",
  "sensitive_zones",
  "talent_links",
  "point_talents",
  "amplified_themes",
  "conscious_axis",
  "background_axis",
  "communication_style",
  "values_and_culture",
  "growth_tension",
  "responsibility_and_rules",
  "work_environment_and_recovery",
  "motivation_and_focus",
  "team_contribution_type",
] as const;

export type RuntimeCoreLayerKey = (typeof RUNTIME_CORE_LAYER_KEYS)[number];

export type ProductLayerKeyV02 =
  | "work_format"
  | "task_entry"
  | "decision_style"
  | "work_signature"
  | "inner_coherence"
  | "stability_and_risk_zones"
  | "talent_links"
  | "point_talents_and_strong_themes"
  | "main_work_axis"
  | "communication_style"
  | "values_and_culture"
  | "growth_tension"
  | "responsibility_and_rules"
  | "work_environment_and_recovery"
  | "motivation_and_focus"
  | "team_contribution_type";

export type SystemLayerKeyV02 = "data_quality";

export type TalentMapLayerKeyV02 = ProductLayerKeyV02 | SystemLayerKeyV02;

export type SynthesisBlockKeyV02 = keyof HrTalentMapSynthesisBlocksV2;

export type ProductLayerRoleV02 = "ai_narrative" | "system_qa";

export type ProductLayerRuntimeStatusV02 =
  | "active_runtime_12"
  | "active_runtime_19"
  | "merged_from_runtime_12"
  | "planned";

export type ProductLayerDefV02 = {
  layer_key: TalentMapLayerKeyV02;
  hr_title: string;
  /** Human-readable HR meaning (product spec). */
  meaning: string;
  /** Technical / chart fields used as evidence (not AI narrative by themselves). */
  source_signals: readonly string[];
  layer_role: ProductLayerRoleV02;
  runtime_status: ProductLayerRuntimeStatusV02;
  /** Runtime layer keys absorbed when merging multiple runtime layers into one product layer. */
  absorbs_runtime_layers?: readonly RuntimeCoreLayerKey[];
  /** Legacy methodology layer keys (pre-v0.2 catalog) folded into this product layer. */
  absorbs_legacy_layer_keys?: readonly LegacyEvidenceLayerKey[];
};

/**
 * Internal methodology catalog: 34 layer keys + chart_passport (UI fallback in talentMapPanelContent).
 * These remain valid as evidence/source signals, not as 34 independent product AI reports.
 */
export const LEGACY_METHODOLOGY_LAYER_KEYS = [
  "chart_passport",
  "work_format",
  "task_entry",
  "decision_style",
  "work_signature",
  "inner_coherence",
  "stable_zones",
  "sensitive_zones",
  "talent_links",
  "point_talents",
  "amplified_themes",
  "personality_activations",
  "design_activations",
  "conscious_axis",
  "background_axis",
  "work_impulse",
  "communication_style",
  "values_and_culture",
  "growth_tension",
  "principles_and_rules",
  "responsibility_maturity",
  "nonstandard_contribution",
  "blind_spots",
  "deep_potential",
  "environment_direction",
  "perception_settings",
  "information_sensing",
  "resource_recovery",
  "driving_motivation",
  "pressure_shift",
  "focus_perspective",
  "focus_distraction",
  "work_environment",
  "team_contribution_type",
  "data_quality",
] as const;

export type LegacyEvidenceLayerKey = (typeof LEGACY_METHODOLOGY_LAYER_KEYS)[number];

export type LegacyEvidenceSignalDefV02 = {
  legacy_layer_key: LegacyEvidenceLayerKey;
  hr_title: string;
  technical_sources: readonly string[];
  /** Primary product layer(s) that consume this signal in v0.2. */
  feeds_product_layers: readonly TalentMapLayerKeyV02[];
  notes?: string;
};

export type VacancyRequirementAreaV02 =
  | "vacancy.responsibilities"
  | "vacancy.work_format"
  | "vacancy.manager_context"
  | "vacancy.communication_requirements"
  | "vacancy.culture"
  | "vacancy.pressure_level"
  | "vacancy.environment"
  | "vacancy.risk_conditions";

/** Sixteen main AI narrative product layers + system QA layer (v0.2). */
export const PRODUCT_LAYER_CATALOG_V0_2: Record<TalentMapLayerKeyV02, ProductLayerDefV02> = {
  work_format: {
    layer_key: "work_format",
    hr_title: "Рабочий формат",
    meaning:
      "Формат энергии, темп, нагрузка, способ включения в работу.",
    source_signals: ["type"],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_12",
  },
  task_entry: {
    layer_key: "task_entry",
    hr_title: "Вход в задачи",
    meaning:
      "Как человеку лучше входить в задачи, предложения и рабочие сценарии.",
    source_signals: ["strategy"],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_12",
  },
  decision_style: {
    layer_key: "decision_style",
    hr_title: "Принятие решений",
    meaning:
      "Как человек принимает рабочие решения; как проверять согласие, готовность и риски.",
    source_signals: ["authority"],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_12",
  },
  work_signature: {
    layer_key: "work_signature",
    hr_title: "Рабочий почерк",
    meaning:
      "Как человек учится, проявляется, набирает доверие, входит в роль.",
    source_signals: ["profile"],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_12",
  },
  inner_coherence: {
    layer_key: "inner_coherence",
    hr_title: "Внутренняя связность",
    meaning:
      "Как человек собирает ясность; насколько ему нужен диалог, среда и синхронизация.",
    source_signals: ["definition"],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_12",
  },
  stability_and_risk_zones: {
    layer_key: "stability_and_risk_zones",
    hr_title: "Устойчивость и зоны перегруза",
    meaning:
      "Где человек устойчив, где зависит от среды, где может перегружаться; что учитывать руководителю.",
    source_signals: [
      "definedCenters",
      "openCenters",
      "notSelfTheme",
      "defined_centers",
      "open_centers",
      "not_self_theme",
    ],
    layer_role: "ai_narrative",
    runtime_status: "merged_from_runtime_12",
    absorbs_runtime_layers: ["stable_zones", "sensitive_zones"],
    absorbs_legacy_layer_keys: ["stable_zones", "sensitive_zones"],
  },
  talent_links: {
    layer_key: "talent_links",
    hr_title: "Связки талантов",
    meaning: "Устойчивые рабочие способности и связки талантов.",
    source_signals: ["channelsShort", "channelsLong", "channels_short", "channels_long"],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_12",
  },
  point_talents_and_strong_themes: {
    layer_key: "point_talents_and_strong_themes",
    hr_title: "Точечные таланты и усиленные темы",
    meaning:
      "Микроталанты, повторяющиеся темы, важные акценты, которые стоит проверить в задачах.",
    source_signals: [
      "gatesAll",
      "gatesPersonality",
      "gatesDesign",
      "gatesBoth",
      "gateSources",
      "gates_all",
      "gates_personality",
      "gates_design",
      "gates_both",
      "gate_sources",
    ],
    layer_role: "ai_narrative",
    runtime_status: "merged_from_runtime_12",
    absorbs_runtime_layers: ["point_talents", "amplified_themes"],
    absorbs_legacy_layer_keys: ["point_talents", "amplified_themes"],
  },
  main_work_axis: {
    layer_key: "main_work_axis",
    hr_title: "Главная рабочая ось",
    meaning:
      "Главный осознанный и фоновый рабочий паттерн кандидата.",
    source_signals: [
      "activations.personality.sun",
      "activations.personality.earth",
      "activations.design.sun",
      "activations.design.earth",
    ],
    layer_role: "ai_narrative",
    runtime_status: "merged_from_runtime_12",
    absorbs_runtime_layers: ["conscious_axis", "background_axis"],
    absorbs_legacy_layer_keys: [
      "conscious_axis",
      "background_axis",
      "personality_activations",
      "design_activations",
    ],
  },
  communication_style: {
    layer_key: "communication_style",
    hr_title: "Коммуникация и объяснение",
    meaning:
      "Как человек объясняет, аргументирует, продаёт идеи и доносит смысл.",
    source_signals: [
      "activations.personality.mercury",
      "activations.design.mercury",
      "channels",
      "gates",
      "throat",
    ],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_19",
    absorbs_runtime_layers: ["communication_style"],
    absorbs_legacy_layer_keys: ["communication_style"],
  },
  values_and_culture: {
    layer_key: "values_and_culture",
    hr_title: "Ценности и культура взаимодействия",
    meaning:
      "Что важно в культуре, отношениях, уважении, договорённостях и стиле команды.",
    source_signals: [
      "activations.personality.venus",
      "activations.design.venus",
      "profile",
      "centers",
      "gates",
    ],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_19",
    absorbs_runtime_layers: ["values_and_culture"],
    absorbs_legacy_layer_keys: ["values_and_culture"],
  },
  growth_tension: {
    layer_key: "growth_tension",
    hr_title: "Напряжение и рост",
    meaning:
      "Где человек может реагировать незрело, торопиться, сопротивляться; что растить.",
    source_signals: [
      "activations.personality.mars",
      "activations.design.mars",
      "openCenters",
      "notSelfTheme",
      "open_centers",
      "not_self_theme",
    ],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_19",
    absorbs_runtime_layers: ["growth_tension"],
    absorbs_legacy_layer_keys: ["growth_tension", "blind_spots", "pressure_shift"],
  },
  responsibility_and_rules: {
    layer_key: "responsibility_and_rules",
    hr_title: "Ответственность, правила и зрелость",
    meaning:
      "Как человек держит правила, ответственность, ограничения и зрелую обратную связь.",
    source_signals: [
      "activations.personality.jupiter",
      "activations.design.jupiter",
      "activations.personality.saturn",
      "activations.design.saturn",
    ],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_19",
    absorbs_runtime_layers: ["responsibility_and_rules"],
    absorbs_legacy_layer_keys: ["principles_and_rules", "responsibility_maturity"],
  },
  work_environment_and_recovery: {
    layer_key: "work_environment_and_recovery",
    hr_title: "Рабочая среда и восстановление",
    meaning:
      "Какая среда помогает работать, что перегружает, какой режим устойчивее. Без медицинских/диетических советов.",
    source_signals: [
      "environment",
      "determination",
      "cognition",
      "variables",
      "centers",
    ],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_19",
    absorbs_runtime_layers: ["work_environment_and_recovery"],
    absorbs_legacy_layer_keys: [
      "environment_direction",
      "perception_settings",
      "information_sensing",
      "resource_recovery",
      "work_environment",
    ],
  },
  motivation_and_focus: {
    layer_key: "motivation_and_focus",
    hr_title: "Мотивация и фокус",
    meaning:
      "Что движет человеком, куда съезжает под давлением, как смотрит на задачи, что сбивает фокус.",
    source_signals: [
      "motivation",
      "transference",
      "perspective",
      "distraction",
      "activations.personality.moon",
      "activations.design.moon",
    ],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_19",
    absorbs_runtime_layers: ["motivation_and_focus"],
    absorbs_legacy_layer_keys: [
      "work_impulse",
      "driving_motivation",
      "focus_perspective",
      "focus_distraction",
    ],
  },
  team_contribution_type: {
    layer_key: "team_contribution_type",
    hr_title: "Тип вклада в команду",
    meaning:
      "Какой вклад человек естественно приносит в команду (индивидуальный, коллективно-логический, опытный, племенной и т.д.).",
    source_signals: ["circuitries", "channels", "profile", "main_work_axis"],
    layer_role: "ai_narrative",
    runtime_status: "active_runtime_19",
    absorbs_runtime_layers: ["team_contribution_type"],
    absorbs_legacy_layer_keys: [
      "team_contribution_type",
      "nonstandard_contribution",
      "deep_potential",
    ],
  },
  data_quality: {
    layer_key: "data_quality",
    hr_title: "Надёжность данных",
    meaning:
      "Качество даты/времени/места рождения, наличие technical chart, ограничения интерпретации, что дозаполнить.",
    source_signals: [
      "data_quality",
      "birthDateUtc",
      "canRenderBodygraph",
      "missingForBodygraph",
    ],
    layer_role: "system_qa",
    runtime_status: "planned",
    absorbs_legacy_layer_keys: ["data_quality", "chart_passport"],
  },
};

export const PRODUCT_LAYER_KEYS_V0_2 = Object.keys(
  PRODUCT_LAYER_CATALOG_V0_2,
) as TalentMapLayerKeyV02[];

export const AI_NARRATIVE_PRODUCT_LAYER_KEYS_V0_2 = PRODUCT_LAYER_KEYS_V0_2.filter(
  (key): key is ProductLayerKeyV02 =>
    PRODUCT_LAYER_CATALOG_V0_2[key].layer_role === "ai_narrative",
);

/**
 * Runtime core layer key (19-step generation) → v0.2 product layer key.
 * Many-to-one merges are resolved on the product side via absorbs_runtime_layers.
 */
export const RUNTIME_CORE_LAYER_TO_PRODUCT_LAYER_V02: Record<
  RuntimeCoreLayerKey,
  ProductLayerKeyV02
> = {
  work_format: "work_format",
  task_entry: "task_entry",
  decision_style: "decision_style",
  work_signature: "work_signature",
  inner_coherence: "inner_coherence",
  stable_zones: "stability_and_risk_zones",
  sensitive_zones: "stability_and_risk_zones",
  talent_links: "talent_links",
  point_talents: "point_talents_and_strong_themes",
  amplified_themes: "point_talents_and_strong_themes",
  conscious_axis: "main_work_axis",
  background_axis: "main_work_axis",
  communication_style: "communication_style",
  values_and_culture: "values_and_culture",
  growth_tension: "growth_tension",
  responsibility_and_rules: "responsibility_and_rules",
  work_environment_and_recovery: "work_environment_and_recovery",
  motivation_and_focus: "motivation_and_focus",
  team_contribution_type: "team_contribution_type",
};

/** Inverse: product layer → runtime keys still emitted today (empty if planned-only). */
export const PRODUCT_LAYER_TO_RUNTIME_CORE_LAYERS_V02: Record<
  ProductLayerKeyV02,
  readonly RuntimeCoreLayerKey[]
> = {
  work_format: ["work_format"],
  task_entry: ["task_entry"],
  decision_style: ["decision_style"],
  work_signature: ["work_signature"],
  inner_coherence: ["inner_coherence"],
  stability_and_risk_zones: ["stable_zones", "sensitive_zones"],
  talent_links: ["talent_links"],
  point_talents_and_strong_themes: ["point_talents", "amplified_themes"],
  main_work_axis: ["conscious_axis", "background_axis"],
  communication_style: ["communication_style"],
  values_and_culture: ["values_and_culture"],
  growth_tension: ["growth_tension"],
  responsibility_and_rules: ["responsibility_and_rules"],
  work_environment_and_recovery: ["work_environment_and_recovery"],
  motivation_and_focus: ["motivation_and_focus"],
  team_contribution_type: ["team_contribution_type"],
};

/** Synthesis blocks → v0.2 layers (16 product + system data_quality where applicable). */
export const SYNTHESIS_BLOCK_LAYERS_V02: Record<
  SynthesisBlockKeyV02,
  readonly TalentMapLayerKeyV02[]
> = {
  executive_summary: [
    "work_format",
    "task_entry",
    "decision_style",
    "work_signature",
    "main_work_axis",
    "talent_links",
    "point_talents_and_strong_themes",
    "stability_and_risk_zones",
    "work_environment_and_recovery",
    "data_quality",
  ],
  work_formula: [
    "work_format",
    "task_entry",
    "decision_style",
    "work_signature",
    "inner_coherence",
    "main_work_axis",
    "talent_links",
    "motivation_and_focus",
  ],
  talents: [
    "talent_links",
    "point_talents_and_strong_themes",
    "main_work_axis",
    "communication_style",
    "values_and_culture",
    "team_contribution_type",
  ],
  work_environment: [
    "work_environment_and_recovery",
    "inner_coherence",
    "stability_and_risk_zones",
    "motivation_and_focus",
    "task_entry",
    "decision_style",
  ],
  risks: [
    "stability_and_risk_zones",
    "growth_tension",
    "responsibility_and_rules",
    "motivation_and_focus",
    "work_environment_and_recovery",
    "data_quality",
  ],
  management: [
    "task_entry",
    "decision_style",
    "work_signature",
    "inner_coherence",
    "stability_and_risk_zones",
    "work_environment_and_recovery",
    "responsibility_and_rules",
    "growth_tension",
    "values_and_culture",
  ],
};

/** AI narrative product layers only (excludes system `data_quality`). */
export const SYNTHESIS_BLOCK_PRODUCT_LAYERS_V02: Record<
  SynthesisBlockKeyV02,
  readonly ProductLayerKeyV02[]
> = {
  executive_summary: [
    "work_format",
    "task_entry",
    "decision_style",
    "work_signature",
    "main_work_axis",
    "talent_links",
    "point_talents_and_strong_themes",
    "stability_and_risk_zones",
    "work_environment_and_recovery",
  ],
  work_formula: [
    "work_format",
    "task_entry",
    "decision_style",
    "work_signature",
    "inner_coherence",
    "main_work_axis",
    "talent_links",
    "motivation_and_focus",
  ],
  talents: [
    "talent_links",
    "point_talents_and_strong_themes",
    "main_work_axis",
    "communication_style",
    "values_and_culture",
    "team_contribution_type",
  ],
  work_environment: [
    "work_environment_and_recovery",
    "inner_coherence",
    "stability_and_risk_zones",
    "motivation_and_focus",
    "task_entry",
    "decision_style",
  ],
  risks: [
    "stability_and_risk_zones",
    "growth_tension",
    "responsibility_and_rules",
    "motivation_and_focus",
    "work_environment_and_recovery",
  ],
  management: [
    "task_entry",
    "decision_style",
    "work_signature",
    "inner_coherence",
    "stability_and_risk_zones",
    "work_environment_and_recovery",
    "responsibility_and_rules",
    "growth_tension",
    "values_and_culture",
  ],
};

/** Product layer → synthesis blocks that consume it (derived inverse). */
export const PRODUCT_LAYER_TO_SYNTHESIS_BLOCKS_V02: Record<
  ProductLayerKeyV02,
  readonly SynthesisBlockKeyV02[]
> = (() => {
  const acc = {} as Record<ProductLayerKeyV02, SynthesisBlockKeyV02[]>;
  for (const key of AI_NARRATIVE_PRODUCT_LAYER_KEYS_V0_2) {
    acc[key] = [];
  }
  for (const [blockKey, layers] of Object.entries(
    SYNTHESIS_BLOCK_PRODUCT_LAYERS_V02,
  ) as Array<[SynthesisBlockKeyV02, readonly ProductLayerKeyV02[]]>) {
    for (const layerKey of layers) {
      acc[layerKey].push(blockKey);
    }
  }
  for (const key of AI_NARRATIVE_PRODUCT_LAYER_KEYS_V0_2) {
    acc[key] = [...new Set(acc[key])].sort();
  }
  return acc;
})();

/** System layer → synthesis blocks (data_quality only today). */
export const SYSTEM_LAYER_TO_SYNTHESIS_BLOCKS_V02: Record<
  SystemLayerKeyV02,
  readonly SynthesisBlockKeyV02[]
> = {
  data_quality: ["executive_summary", "risks"],
};

/**
 * Future role-fit: vacancy requirement areas → v0.2 product layers.
 * Role-fit should compare matching_summary / requirement_summary, not full layer_reports.
 */
export const VACANCY_REQUIREMENT_TO_PRODUCT_LAYERS_V02: Record<
  VacancyRequirementAreaV02,
  readonly ProductLayerKeyV02[]
> = {
  "vacancy.responsibilities": [
    "talent_links",
    "point_talents_and_strong_themes",
    "main_work_axis",
  ],
  "vacancy.work_format": ["work_format", "task_entry", "decision_style"],
  "vacancy.manager_context": [
    "work_signature",
    "inner_coherence",
    "stability_and_risk_zones",
    "responsibility_and_rules",
  ],
  "vacancy.communication_requirements": ["communication_style", "values_and_culture"],
  "vacancy.culture": ["values_and_culture", "team_contribution_type"],
  "vacancy.pressure_level": [
    "stability_and_risk_zones",
    "growth_tension",
    "motivation_and_focus",
  ],
  "vacancy.environment": ["work_environment_and_recovery", "motivation_and_focus"],
  "vacancy.risk_conditions": [
    "growth_tension",
    "stability_and_risk_zones",
    "responsibility_and_rules",
  ],
};

/**
 * Legacy methodology layer catalog as evidence/source signals (mirrors UI fallback catalog).
 * chart_passport is meta/evidence, not a standalone product AI narrative layer.
 */
export const EVIDENCE_SIGNAL_CATALOG_V0_2: LegacyEvidenceSignalDefV02[] = [
  {
    legacy_layer_key: "chart_passport",
    hr_title: "Паспорт рабочей карты",
    technical_sources: [
      "type",
      "profile",
      "strategy",
      "authority",
      "definition",
      "incarnationCross",
      "signature",
      "notSelfTheme",
    ],
    feeds_product_layers: ["data_quality"],
    notes: "Meta summary signal; folded into data_quality / executive context, not a product AI layer.",
  },
  {
    legacy_layer_key: "work_format",
    hr_title: "Рабочий формат",
    technical_sources: ["type"],
    feeds_product_layers: ["work_format"],
  },
  {
    legacy_layer_key: "task_entry",
    hr_title: "Вход в задачи",
    technical_sources: ["strategy"],
    feeds_product_layers: ["task_entry"],
  },
  {
    legacy_layer_key: "decision_style",
    hr_title: "Принятие решений",
    technical_sources: ["authority"],
    feeds_product_layers: ["decision_style"],
  },
  {
    legacy_layer_key: "work_signature",
    hr_title: "Рабочий почерк",
    technical_sources: ["profile"],
    feeds_product_layers: ["work_signature"],
  },
  {
    legacy_layer_key: "inner_coherence",
    hr_title: "Внутренняя связность",
    technical_sources: ["definition"],
    feeds_product_layers: ["inner_coherence"],
  },
  {
    legacy_layer_key: "stable_zones",
    hr_title: "Устойчивые зоны",
    technical_sources: ["definedCenters"],
    feeds_product_layers: ["stability_and_risk_zones"],
  },
  {
    legacy_layer_key: "sensitive_zones",
    hr_title: "Чувствительные зоны",
    technical_sources: ["openCenters"],
    feeds_product_layers: ["stability_and_risk_zones"],
  },
  {
    legacy_layer_key: "talent_links",
    hr_title: "Связки талантов",
    technical_sources: ["channelsShort", "channelsLong"],
    feeds_product_layers: ["talent_links"],
  },
  {
    legacy_layer_key: "point_talents",
    hr_title: "Точечные таланты",
    technical_sources: ["gatesAll", "gatesPersonality", "gatesDesign", "gateSources"],
    feeds_product_layers: ["point_talents_and_strong_themes"],
  },
  {
    legacy_layer_key: "amplified_themes",
    hr_title: "Усиленные темы",
    technical_sources: ["gatesBoth", "gateSources"],
    feeds_product_layers: ["point_talents_and_strong_themes"],
  },
  {
    legacy_layer_key: "personality_activations",
    hr_title: "Сознательный слой проявления",
    technical_sources: ["activations.personality"],
    feeds_product_layers: ["main_work_axis", "communication_style", "motivation_and_focus"],
  },
  {
    legacy_layer_key: "design_activations",
    hr_title: "Фоновый слой проявления",
    technical_sources: ["activations.design"],
    feeds_product_layers: ["main_work_axis", "work_environment_and_recovery"],
  },
  {
    legacy_layer_key: "conscious_axis",
    hr_title: "Сознательная рабочая ось",
    technical_sources: ["activations.personality.sun", "activations.personality.earth"],
    feeds_product_layers: ["main_work_axis"],
  },
  {
    legacy_layer_key: "background_axis",
    hr_title: "Фоновая рабочая ось",
    technical_sources: ["activations.design.sun", "activations.design.earth"],
    feeds_product_layers: ["main_work_axis"],
  },
  {
    legacy_layer_key: "work_impulse",
    hr_title: "Рабочий импульс",
    technical_sources: ["activations.personality.moon", "activations.design.moon"],
    feeds_product_layers: ["motivation_and_focus"],
  },
  {
    legacy_layer_key: "communication_style",
    hr_title: "Коммуникация и объяснение",
    technical_sources: ["activations.personality.mercury", "activations.design.mercury"],
    feeds_product_layers: ["communication_style"],
  },
  {
    legacy_layer_key: "values_and_culture",
    hr_title: "Ценности и культура взаимодействия",
    technical_sources: ["activations.personality.venus", "activations.design.venus"],
    feeds_product_layers: ["values_and_culture"],
  },
  {
    legacy_layer_key: "growth_tension",
    hr_title: "Напряжение и рост",
    technical_sources: ["activations.personality.mars", "activations.design.mars"],
    feeds_product_layers: ["growth_tension"],
  },
  {
    legacy_layer_key: "principles_and_rules",
    hr_title: "Принципы и правила",
    technical_sources: ["activations.personality.jupiter", "activations.design.jupiter"],
    feeds_product_layers: ["responsibility_and_rules"],
  },
  {
    legacy_layer_key: "responsibility_maturity",
    hr_title: "Ответственность и зрелость",
    technical_sources: ["activations.personality.saturn", "activations.design.saturn"],
    feeds_product_layers: ["responsibility_and_rules"],
  },
  {
    legacy_layer_key: "nonstandard_contribution",
    hr_title: "Нестандартный вклад",
    technical_sources: ["activations.personality.uranus", "activations.design.uranus"],
    feeds_product_layers: ["team_contribution_type"],
  },
  {
    legacy_layer_key: "blind_spots",
    hr_title: "Слепые зоны",
    technical_sources: ["activations.personality.neptune", "activations.design.neptune"],
    feeds_product_layers: ["growth_tension"],
  },
  {
    legacy_layer_key: "deep_potential",
    hr_title: "Глубинный потенциал",
    technical_sources: ["activations.personality.pluto", "activations.design.pluto"],
    feeds_product_layers: ["team_contribution_type", "talent_links"],
  },
  {
    legacy_layer_key: "environment_direction",
    hr_title: "Среда и направление",
    technical_sources: [
      "activations.personality.northNode",
      "activations.personality.southNode",
      "activations.design.northNode",
      "activations.design.southNode",
    ],
    feeds_product_layers: ["work_environment_and_recovery"],
  },
  {
    legacy_layer_key: "perception_settings",
    hr_title: "Настройка восприятия",
    technical_sources: ["variables"],
    feeds_product_layers: ["work_environment_and_recovery"],
  },
  {
    legacy_layer_key: "information_sensing",
    hr_title: "Способ считывания",
    technical_sources: ["cognition"],
    feeds_product_layers: ["work_environment_and_recovery"],
  },
  {
    legacy_layer_key: "resource_recovery",
    hr_title: "Ресурс и восстановление",
    technical_sources: ["determination"],
    feeds_product_layers: ["work_environment_and_recovery"],
  },
  {
    legacy_layer_key: "driving_motivation",
    hr_title: "Движущая мотивация",
    technical_sources: ["motivation"],
    feeds_product_layers: ["motivation_and_focus"],
  },
  {
    legacy_layer_key: "pressure_shift",
    hr_title: "Сдвиг под давлением",
    technical_sources: ["transference"],
    feeds_product_layers: ["motivation_and_focus", "growth_tension"],
  },
  {
    legacy_layer_key: "focus_perspective",
    hr_title: "Фокус взгляда",
    technical_sources: ["perspective"],
    feeds_product_layers: ["motivation_and_focus"],
  },
  {
    legacy_layer_key: "focus_distraction",
    hr_title: "Что сбивает фокус",
    technical_sources: ["distraction"],
    feeds_product_layers: ["motivation_and_focus"],
  },
  {
    legacy_layer_key: "work_environment",
    hr_title: "Рабочая среда",
    technical_sources: ["environment"],
    feeds_product_layers: ["work_environment_and_recovery"],
  },
  {
    legacy_layer_key: "team_contribution_type",
    hr_title: "Тип вклада в команду",
    technical_sources: ["circuitries"],
    feeds_product_layers: ["team_contribution_type"],
  },
  {
    legacy_layer_key: "data_quality",
    hr_title: "Надёжность данных",
    technical_sources: [
      "data_quality",
      "birthDateUtc",
      "canRenderBodygraph",
      "missingForBodygraph",
    ],
    feeds_product_layers: ["data_quality"],
  },
];

/** Alias used in Stage 4.7 spec wording. */
export const SOURCE_SIGNAL_CATALOG_V0_2 = EVIDENCE_SIGNAL_CATALOG_V0_2;

export function resolveProductLayerForRuntimeKey(
  runtimeLayerKey: string,
): ProductLayerKeyV02 | null {
  if (!(RUNTIME_CORE_LAYER_KEYS as readonly string[]).includes(runtimeLayerKey)) {
    return null;
  }
  return RUNTIME_CORE_LAYER_TO_PRODUCT_LAYER_V02[runtimeLayerKey as RuntimeCoreLayerKey];
}

export function isRuntimeCoreLayerKey(key: string): key is RuntimeCoreLayerKey {
  return (RUNTIME_CORE_LAYER_KEYS as readonly string[]).includes(key);
}
